version: '3'


services:
    traefik:
        image: traefik
        command: --web --docker --docker.exposedbydefault=false --logLevel=DEBUG --web.metrics.prometheus
        ports:
            - 80:80
            - 8080:8080
        labels:
            - "bleemeo.stack=bleemeoquote"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml
        restart: unless-stopped

    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        labels:
            - "traefik.backend=nginx"
            - "traefik.frontend.rule=Host:quote.bleemeo.com"
            - "traefik.enable=true"
            - "bleemeo.stack=bleemeoquote"
        restart: unless-stopped

    uwsgi:
        build:
            context: .
            dockerfile: Dockerfile
        labels:
            - "bleemeo.stack=bleemeoquote"
        environment:
            - DJANGO_SETTINGS_MODULE=bleemeo_quote.settings.production
        restart: unless-stopped

    postgresql:
        image: postgres:11
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=bleemeo_quote_user
            - POSTGRES_DB=bleemeo_quote
        labels:
            - "bleemeo.stack=bleemeoquote"
        restart: unless-stopped

    redis:
        image: redis:5.0.4
        labels:
            - "bleemeo.stack=bleemeoquote"
        restart: unless-stopped
