apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: bleemeo_quote
  POSTGRES_USER: bleemeo_quote_user
  POSTGRES_PASSWORD: admin123
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        bleemeo.stack: quote
    spec:
      containers:
        - name: postgres
          image: postgres:13.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          hostPath:
            path: /mnt/data
            type: DirectoryOrCreate
