apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: quote
  name: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      run: quote
  template:
    metadata:
      labels:
        run: quote
      annotations:
        bleemeo.stack: quote
    spec:
      containers:
      - image: bleemeolabs/quote:latest-arm
        imagePullPolicy: IfNotPresent
        name: quote
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "bleemeo_quote.settings.production"
        - name: DJANGO_DATABASE_PASSWORD
          value: "admin123"
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: quote
  name: quote
spec:
  selector:
    run: quote
  ports:
  - port: 8181
    protocol: TCP
    targetPort: 8181
