apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: quote
  name: quote
  annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8181"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: quote
  template:
    metadata:
      labels:
        name: quote
      annotations:
        bleemeo.stack: quote
        prometheus.io/scrape: "true"
        prometheus.io/port: "8181"
    spec:
      containers:
      - image: ghcr.io/bleemeolabs/quote:latest
        imagePullPolicy: IfNotPresent
        name: quote
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "bleemeo_quote.settings.production"
        - name: DJANGO_DATABASE_PASSWORD
          value: "admin123"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: quote
  name: quote
spec:
  type: NodePort
  ports:
  - port: 8181
    protocol: TCP
    targetPort: 8181
    nodePort: 30003
  selector:
    name: quote
